"""empty message

Revision ID: 122246be18cf
Revises: 4de6d25634e7
Create Date: 2021-06-21 23:29:58.136999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122246be18cf'
down_revision = '4de6d25634e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # nullable True allows changes to be applied to previous records that don't have this value yet.

    # Adds False value to preexisting records and sets constraints (nullable to False)
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
