"""empty message

Revision ID: 2a942a12e197
Revises: 122246be18cf
Create Date: 2021-06-24 11:48:56.723601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a942a12e197'
down_revision = '122246be18cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
